version: "3.8"

services:
  postgres:
    restart: always
    container_name: mo_postgres
    image: postgres:13
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  django_backend:
    env_file:
      - ./.env
    container_name: django_backend
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/src/entrypoint
    command: /app/src/start
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - .:/app/src
    depends_on:
      - postgres
    restart: on-failure
