#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Running Database Migrations"
python mo_tech/manage.py makemigrations
python mo_tech/manage.py migrate
exec python mo_tech/manage.py runserver 0.0.0.0:8000
