# Generated by Django 4.2.6 on 2023-10-18 20:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=60, unique=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Active"), (2, "Inactive")], default=1
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("preapproved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
